//> using lib "com.lihaoyi::os-lib:0.9.1"
//> using lib "io.github.quafadas::scautable:0.0.5"
//> using lib "io.github.quafadas::dedav4s:0.9.0-RC1"
//> using lib "com.lihaoyi::upickle:3.1.0"
//> using lib "co.fs2::fs2-core:3.6.1"
